name: Generate Snake

on:
  schedule:
    # 每天午夜运行
    - cron: "0 0 * * *"
  
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v2
      
      # 生成贪吃蛇动画
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # 生成 SVG 格式的贪吃蛇动画
          svg_out_path: dist/github-contribution-grid-snake.svg
          # 可选：生成 GIF 格式的贪吃蛇动画
          # gif_out_path: dist/github-contribution-grid-snake.gif

      # 将生成的动画推送到输出分支
      - uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 